INSERT INTO users (name, email, password) VALUES ('Eva Stanley', 'eva@xmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
INSERT INTO users (name, email, password) VALUES ('Louis Kalr', 'kalr@xmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
INSERT INTO users (name, email, password) VALUES ('Rita Moraes', 'rmor@xmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
INSERT INTO users (name, email, password) VALUES ('Etta Wong', 'etta@xmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');
INSERT INTO users (name, email, password) VALUES ('Leroy Myker', 'leroy@xmail.com', '$2a$10$FB/BOAVhpuLvpOREQVmvmezD4ED/.JBIDRh70tGevYzYzQgFId2u.');

INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (1, 'Speed lamp', 'description', 'https://images.unsplash.com/photo-1578427416100-1c0934bf08f0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60', 'https://images.unsplash.com/photo-1578427416100-1c0934bf08f0?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60', 120, 1, 1, 2, 'Canada', '23 Hugah', 'Ottawa', 'ON', 'K2W5G7', TRUE);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (1, 'Habit mix', 'description', 'https://images.pexels.com/photos/50577/hedgehog-animal-baby-cute-50577.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260', 'https://images.pexels.com/photos/50577/hedgehog-animal-baby-cute-50577.jpeg?auto=compress&cs=tinysrgb&dpr=3&h=750&w=1260',130, 1, 1, 2, 'Canada', '223 Namsub', 'Ottawa', 'ON', 'K2W5G7', TRUE);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (2, 'Port out', 'description', 'https://images.pexels.com/photos/39317/chihuahua-dog-puppy-cute-39317.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://images.pexels.com/photos/39317/chihuahua-dog-puppy-cute-39317.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 125, 1, 1, 2, 'Canada', '237 Highway', 'Ottawa', 'ON', 'K2W5G7', FALSE);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (4, 'Blank corner', 'description', 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://images.pexels.com/photos/1108099/pexels-photo-1108099.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 127, 2, 1, 2, 'Canada', '323 Nilson St', 'Ottawa', 'ON', 'K2W5G7', TRUE);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (3, 'Headed know', 'description', 'https://images.pexels.com/photos/127027/pexels-photo-127027.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://images.pexels.com/photos/127027/pexels-photo-127027.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 320, 1, 1, 2, 'Canada', '123 Gurkam', 'Ottawa', 'ON', 'K2W5G7', TRUE);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (3, 'Shine twenty', 'description', 'https://images.pexels.com/photos/64219/dolphin-marine-mammals-water-sea-64219.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://images.pexels.com/photos/64219/dolphin-marine-mammals-water-sea-64219.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 520, 2, 1, 2, 'Canada', '6623 March Road', 'Ottawa', 'ON', 'K2W5G7', TRUE);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (5, 'Speed lamp', 'description', 'https://images.pexels.com/photos/148182/pexels-photo-148182.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://images.pexels.com/photos/148182/pexels-photo-148182.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 340, 1, 1, 2, 'Canada', '273 Merlin', 'Ottawa', 'ON', 'K2W5G7', TRUE);
INSERT INTO properties (owner_id, title, description, thumbnail_photo_url, cover_photo_url, cost_per_night, parking_spaces, number_of_bathrooms, number_of_bedrooms, country, street, city, province, post_code, active) VALUES (1, 'Game fill', 'description', 'https://images.pexels.com/photos/374898/pexels-photo-374898.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 'https://images.pexels.com/photos/374898/pexels-photo-374898.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500', 341, 1, 1, 2, 'Canada', '953 Google', 'Ottawa', 'ON', 'K2W5G7', TRUE);

INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2018-09-11', '2018-09-26', 2, 2);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2019-08-16', '2019-08-20', 1, 3);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2020-07-16', '2020-07-23', 3, 4);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2019-06-13', '2019-06-28', 4, 1);
INSERT INTO reservations (start_date, end_date, property_id, guest_id) VALUES ('2020-05-02', '2020-05-30', 5, 2);

INSERT INTO property_reviews(guest_id, property_id, reservation_id, rating, message) VALUES (2, 2, 1, 3, 'messages');
INSERT INTO property_reviews(guest_id, property_id, reservation_id, rating, message) VALUES (1, 1, 1, 4, 'messages');
INSERT INTO property_reviews(guest_id, property_id, reservation_id, rating, message) VALUES (2, 2, 2, 5, 'messages');
INSERT INTO property_reviews(guest_id, property_id, reservation_id, rating, message) VALUES (3, 3, 2, 3, 'messages');
INSERT INTO property_reviews(guest_id, property_id, reservation_id, rating, message) VALUES (4, 4, 3, 4, 'messages');
INSERT INTO property_reviews(guest_id, property_id, reservation_id, rating, message) VALUES (2, 4, 2, 2, 'messages');